version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      BACKEND_PORT: 8080

  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_URL: http://backend:8080
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
